@startuml
skinparam ConditionEndStyle hline

title Flowchart Peminjaman Buku (Sensor Kamera & Lokasi)

start
:User Login & Masuk Dashboard;
:Pilih Menu Daftar Buku;
:Pilih Buku yg Mau Dipinjam;

if (Stok Tersedia?) then (Ya)
    :Request Izin Kamera & Lokasi;
    if (Izin Diberikan?) then (Ya)
        :Buka Kamera Viewfinder;
        :Ambil Foto Selfie & Koordinat GPS;
        :Klik Tombol Pinjam;
        partition "Database Process" {
            :Simpan Data Peminjaman,\nFoto & Lokasi;
            :Update Stok Buku;
        }
        :Tampilkan: Peminjaman Berhasil;
    else (Tidak)
        #pink:Error: Kamera & GPS Wajib Aktif;
        detach
    endif
else (Tidak)
    #pink:Tampilkan: Stok Habis;
    :Kembali ke Daftar Buku;
endif

stop
@enduml