@startuml

'--- FLOWCHART 1: PEMINJAMAN BUKU (BORROW) ---
title Flowchart 1: Peminjaman Buku (Fokus: Stok & Kamera)

start
:User Login & Masuk Dashboard;
:Pilih Menu Daftar Buku;
repeat
  :Pilih Buku yg Mau Dipinjam;
  if (Stok Tersedia?) then (Tidak)
    :Tampilkan: Stok Habis;
  else (Ya)
    break
  endif
repeat while (Stok Kosong?)

:Request Izin Kamera;

if (Izin Diberikan?) then (Tidak)
  :Error: Kamera Wajib Aktif;
  stop
else (Ya)
  :Buka Kamera Viewfinder;
  :Ambil Foto Selfie/Bukti;
  :Klik Tombol Pinjam;
  :Simpan Data Peminjaman\n& Upload Foto (Database);
  :Kurangi Stok Buku (Database);
  :Tampilkan: Peminjaman Berhasil;
  stop
endif

@enduml


@startuml

'--- FLOWCHART 2: PENGEMBALIAN BUKU (RETURN) ---
title Flowchart 2: Pengembalian Buku (Fokus: Lokasi & Kamera)

start
:Pilih Menu Riwayat Peminjaman;
:Pilih Transaksi Aktif;
:Klik Tombol 'Kembalikan Buku';
:System Request: Akses Lokasi GPS;

if (Validasi Lokasi:\nUser di Area Perpus?) then (Tidak / Di Luar Area)
  :Alert: Gagal! Anda harus berada\ndi Perpustakaan;
  stop
else (Ya / Di Dalam Area)
  :Request Izin Kamera;
  :Buka Kamera;
  :Ambil Foto Kondisi Buku;
  :Update Status: Dikembalikan\nSimpan Lokasi & Foto (Database);
  :Tambah Stok Buku (Database);
  :Tampilkan: Pengembalian Berhasil;
  stop
endif

@enduml