@startuml
left to right direction
skinparam packageStyle rectangle

' --- Definisi Aktor ---
actor "Peminjam" as user
actor "Admin Pustakawan" as admin

' --- Batas Sistem ---
rectangle "Sistem Peminjaman Perpustakaan" {

  ' --- Use Case Autentikasi (Modul 6 & 7) ---
  usecase "Login" as UC_Login
  usecase "Register Akun" as UC_Register
  usecase "Logout" as UC_Logout

  ' --- Use Case User/Mahasiswa ---
  usecase "Lihat Daftar & Stok Buku" as UC_Search
  usecase "Pinjam Buku (Borrow)" as UC_Borrow
  usecase "Kembalikan Buku (Return)" as UC_Return
  usecase "Lihat Riwayat Peminjaman" as UC_History

  ' --- Use Case Admin ---
  usecase "Kelola Data Buku (CRUD)" as UC_ManageItems
  usecase "Lihat Laporan Peminjaman" as UC_Report

  ' --- Use Case Teknis (Fitur Utama Modul 9 & 10) ---
  usecase "Ambil Foto Selfie (Bukti)" as UC_Selfie
  usecase "Ambil & Validasi Lokasi" as UC_GPS

}

' --- Relasi Aktor ke Use Case ---

' User Interactions
user --> UC_Register
user --> UC_Login
user --> UC_Logout
user --> UC_Search
user --> UC_Borrow
user --> UC_Return
user --> UC_History

' Admin Interactions
admin --> UC_Login
admin --> UC_Logout
admin --> UC_ManageItems
admin --> UC_Report

' --- Relasi Include (Wajib Dilakukan) ---
' Saat Pinjam atau Kembali, WAJIB Selfie & Cek Lokasi

UC_Borrow ..> UC_Selfie : <<include>>
UC_Borrow ..> UC_GPS : <<include>>

UC_Return ..> UC_Selfie : <<include>>
UC_Return ..> UC_GPS : <<include>>



@enduml