@startuml
title Activity Diagram - Login & Logout Pustakawan

|Pustakawan|
start
:Input Email & Password Admin;

|Sistem|
repeat
  :Cek Database (Role Admin);
  if (Valid?) then (Ya)
    :Set Session Role 'Admin';
    break
  else (Tidak)
    :Tampilkan Alert Error;
    |Pustakawan|
    :Input Kredensial;
    |Sistem|
  endif
repeat while (Login)

:Tampilkan Dashboard Admin;
|Pustakawan|
:Pilih Logout;
|Sistem|
:Hapus Session & Redirect ke Login;
stop
@enduml