@startuml
left to right direction
skinparam packageStyle rectangle

actor "Peminjam" as user
actor "Admin Pustakawan" as admin

rectangle "Sistem Peminjaman Buku Perpustakaan" {
    ' Use Case Peminjam
    usecase "Registrasi User" as UC_Reg_User
    usecase "Login User" as UC_Login_User
    usecase "Kembalikan Buku" as UC_Return
    usecase "Pinjam Buku" as UC_Borrow
    usecase "Lihat Daftar Buku" as UC_Search
    usecase "Logout User" as UC_Logout_User
    usecase "Riwayat Peminjaman" as UC_History

    ' Use Case Admin
    usecase "Registrasi Admin" as UC_Reg_Admin
    usecase "Login Admin" as UC_Login_Admin
    usecase "Logout Admin" as UC_Logout_Admin
    usecase "Lihat Laporan" as UC_Report
    usecase "Kelola Buku" as UC_Manage

    ' Use Case Teknis
    usecase "Validasi Foto & Lokasi" as UC_Tech
}

' --- Relasi Peminjam ---
user --> UC_Reg_User
UC_Reg_User ..> UC_Login_User : <<include>>
UC_Login_User ..> UC_Return : <<include>>
UC_Login_User ..> UC_Borrow : <<include>>
UC_Login_User ..> UC_Search : <<include>>
UC_Login_User ..> UC_Logout_User : <<include>>
UC_Login_User ..> UC_History : <<include>>

' --- Relasi Validasi ---
UC_Return ..> UC_Tech : <<include>>
UC_Borrow ..> UC_Tech : <<include>>

' --- Relasi Admin ---
admin --> UC_Reg_Admin
UC_Reg_Admin ..> UC_Login_Admin : <<include>>
UC_Login_Admin ..> UC_Logout_Admin : <<include>>
UC_Login_Admin ..> UC_Report : <<include>>
UC_Login_Admin ..> UC_Manage : <<include>>

@enduml